runtime: python37

handlers:
  - url: /
    static_files: static/index.html
    upload: static/index.html
  - url: /(.*\.(gif|png|jpg|js|css|json|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|js|css|json|txt)$
  - url: /.*
    script: auto

automatic_scaling:
  max_instances: 1
  min_instances: 0
