# This workflow will build and push a new container image to GitHub Docker Registry
on: push

name: Deploy to GitHub Registry

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build, tag, and push image to Github Docker Registry
      id: build-image
      env:
        REGISTRY: docker.pkg.github.com
        REPOSITORY: ${{ github.repository }}
        USERNAME: ${{secrets.docker_username}}
        IMAGE_TAG: wordgame-api:latest
      run: |
        # Build a docker container and tag
        docker login $REGISTRY -u ${{secrets.docker_username}} -p ${{secrets.GITHUB_TOKEN}}
        docker build . --tag $IMAGE_TAG
        docker tag wordgame-api $REGISTRY/$REPOSITORY/$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY/$IMAGE_TAG
